import "./globals.css";
import Providers from "./providers";
import Navbar from "@/components/Navbar";
import Hero from "@/components/Hero";
import ServicesText from "@/components/ServicesText";
import Portfolio from "@/components/Portfolio";
export const metadata = {
  title: "Rakhymzhan Turlybek Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="px-10  min-h-screen md:px-20 lg:px-30">
        <Providers>
          <Navbar />
          <Hero />
          <ServicesText />
          <Portfolio />
        </Providers>
      </body>
    </html>
  );
}
